// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlc

import (
	"context"
)

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = ?, available_balance = ?
WHERE id = ?
`

type UpdateAccountBalanceParams struct {
	Balance          uint64 `json:"balance"`
	AvailableBalance uint64 `json:"available_balance"`
	ID               int32  `json:"id"`
}

// 계좌 잔고/가용잔고 갱신. 최종 값으로 덮어쓰므로 멱등.
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.exec(ctx, q.updateAccountBalanceStmt, updateAccountBalance, arg.Balance, arg.AvailableBalance, arg.ID)
	return err
}
