// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlc

import (
	"context"
)

const activateAccount = `-- name: ActivateAccount :exec
UPDATE accounts
SET status = 'ACTIVE'
WHERE id = ?
`

func (q *Queries) ActivateAccount(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.activateAccountStmt, activateAccount, id)
	return err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = ?, available_balance = ?
WHERE id = ?
`

type UpdateAccountBalanceParams struct {
	Balance          uint64 `json:"balance"`
	AvailableBalance uint64 `json:"available_balance"`
	ID               int32  `json:"id"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.exec(ctx, q.updateAccountBalanceStmt, updateAccountBalance, arg.Balance, arg.AvailableBalance, arg.ID)
	return err
}
