// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeAdminRequest = `-- name: CompleteAdminRequest :exec
UPDATE admin_requests
SET status = 'COMPLETED', completed_at = ?
WHERE id = ?
`

type CompleteAdminRequestParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) CompleteAdminRequest(ctx context.Context, arg CompleteAdminRequestParams) error {
	_, err := q.exec(ctx, q.completeAdminRequestStmt, completeAdminRequest, arg.CompletedAt, arg.ID)
	return err
}

const rejectAdminRequest = `-- name: RejectAdminRequest :exec
UPDATE admin_requests
SET status = 'REJECTED', reject_reason = ?, completed_at = ?
WHERE id = ?
`

type RejectAdminRequestParams struct {
	RejectReason NullAdminRequestsRejectReason `json:"reject_reason"`
	CompletedAt  sql.NullTime                  `json:"completed_at"`
	ID           int64                         `json:"id"`
}

func (q *Queries) RejectAdminRequest(ctx context.Context, arg RejectAdminRequestParams) error {
	_, err := q.exec(ctx, q.rejectAdminRequestStmt, rejectAdminRequest, arg.RejectReason, arg.CompletedAt, arg.ID)
	return err
}
