// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursor.sql

package sqlc

import (
	"context"
)

const loadDBAppliedCursor = `-- name: LoadDBAppliedCursor :one
SELECT ` + "`" + `index` + "`" + `
FROM ` + "`" + `cursors` + "`" + `
WHERE ` + "`" + `type` + "`" + ` = 'DB_APPLIED_OUTPUT_SEQ'
`

func (q *Queries) LoadDBAppliedCursor(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.loadDBAppliedCursorStmt, loadDBAppliedCursor)
	var index int64
	err := row.Scan(&index)
	return index, err
}

const loadMQPublishedCursor = `-- name: LoadMQPublishedCursor :one
SELECT ` + "`" + `index` + "`" + `
FROM ` + "`" + `cursors` + "`" + `
WHERE ` + "`" + `type` + "`" + ` = 'MQ_PUBLISHED_OUTPUT_SEQ'
`

func (q *Queries) LoadMQPublishedCursor(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.loadMQPublishedCursorStmt, loadMQPublishedCursor)
	var index int64
	err := row.Scan(&index)
	return index, err
}

const saveDBAppliedCursor = `-- name: SaveDBAppliedCursor :exec
INSERT INTO ` + "`" + `cursors` + "`" + ` (` + "`" + `type` + "`" + `, ` + "`" + `index` + "`" + `)
VALUES ('DB_APPLIED_OUTPUT_SEQ', ?)
ON DUPLICATE KEY UPDATE ` + "`" + `index` + "`" + ` = VALUES(` + "`" + `index` + "`" + `)
`

func (q *Queries) SaveDBAppliedCursor(ctx context.Context, index int64) error {
	_, err := q.exec(ctx, q.saveDBAppliedCursorStmt, saveDBAppliedCursor, index)
	return err
}

const saveMQPublishedCursor = `-- name: SaveMQPublishedCursor :exec
INSERT INTO ` + "`" + `cursors` + "`" + ` (` + "`" + `type` + "`" + `, ` + "`" + `index` + "`" + `)
VALUES ('MQ_PUBLISHED_OUTPUT_SEQ', ?)
ON DUPLICATE KEY UPDATE ` + "`" + `index` + "`" + ` = VALUES(` + "`" + `index` + "`" + `)
`

func (q *Queries) SaveMQPublishedCursor(ctx context.Context, index int64) error {
	_, err := q.exec(ctx, q.saveMQPublishedCursorStmt, saveMQPublishedCursor, index)
	return err
}
