// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursor.sql

package sqlc

import (
	"context"
)

const loadCursor = `-- name: LoadCursor :one
SELECT ` + "`" + `index` + "`" + ` FROM ` + "`" + `cursors` + "`" + ` WHERE ` + "`" + `type` + "`" + ` = ?
`

func (q *Queries) LoadCursor(ctx context.Context, type_ CursorsType) (int64, error) {
	row := q.queryRow(ctx, q.loadCursorStmt, loadCursor, type_)
	var index int64
	err := row.Scan(&index)
	return index, err
}

const saveCursor = `-- name: SaveCursor :exec
INSERT INTO ` + "`" + `cursors` + "`" + ` (` + "`" + `type` + "`" + `, ` + "`" + `index` + "`" + `)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE ` + "`" + `index` + "`" + ` = VALUES(` + "`" + `index` + "`" + `)
`

type SaveCursorParams struct {
	Type  CursorsType `json:"type"`
	Index int64       `json:"index"`
}

func (q *Queries) SaveCursor(ctx context.Context, arg SaveCursorParams) error {
	_, err := q.exec(ctx, q.saveCursorStmt, saveCursor, arg.Type, arg.Index)
	return err
}
