// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.latestSnapshotStmt, err = db.PrepareContext(ctx, latestSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query LatestSnapshot: %w", err)
	}
	if q.loadCursorStmt, err = db.PrepareContext(ctx, loadCursor); err != nil {
		return nil, fmt.Errorf("error preparing query LoadCursor: %w", err)
	}
	if q.saveCursorStmt, err = db.PrepareContext(ctx, saveCursor); err != nil {
		return nil, fmt.Errorf("error preparing query SaveCursor: %w", err)
	}
	if q.saveSnapshotStmt, err = db.PrepareContext(ctx, saveSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query SaveSnapshot: %w", err)
	}
	if q.saveTradeStmt, err = db.PrepareContext(ctx, saveTrade); err != nil {
		return nil, fmt.Errorf("error preparing query SaveTrade: %w", err)
	}
	if q.updateOrderStatusStmt, err = db.PrepareContext(ctx, updateOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.latestSnapshotStmt != nil {
		if cerr := q.latestSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing latestSnapshotStmt: %w", cerr)
		}
	}
	if q.loadCursorStmt != nil {
		if cerr := q.loadCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing loadCursorStmt: %w", cerr)
		}
	}
	if q.saveCursorStmt != nil {
		if cerr := q.saveCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveCursorStmt: %w", cerr)
		}
	}
	if q.saveSnapshotStmt != nil {
		if cerr := q.saveSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveSnapshotStmt: %w", cerr)
		}
	}
	if q.saveTradeStmt != nil {
		if cerr := q.saveTradeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveTradeStmt: %w", cerr)
		}
	}
	if q.updateOrderStatusStmt != nil {
		if cerr := q.updateOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	latestSnapshotStmt    *sql.Stmt
	loadCursorStmt        *sql.Stmt
	saveCursorStmt        *sql.Stmt
	saveSnapshotStmt      *sql.Stmt
	saveTradeStmt         *sql.Stmt
	updateOrderStatusStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		latestSnapshotStmt:    q.latestSnapshotStmt,
		loadCursorStmt:        q.loadCursorStmt,
		saveCursorStmt:        q.saveCursorStmt,
		saveSnapshotStmt:      q.saveSnapshotStmt,
		saveTradeStmt:         q.saveTradeStmt,
		updateOrderStatusStmt: q.updateOrderStatusStmt,
	}
}
