// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateAccountStmt, err = db.PrepareContext(ctx, activateAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateAccount: %w", err)
	}
	if q.deleteHoldingStmt, err = db.PrepareContext(ctx, deleteHolding); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHolding: %w", err)
	}
	if q.latestSnapshotStmt, err = db.PrepareContext(ctx, latestSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query LatestSnapshot: %w", err)
	}
	if q.loadDBAppliedCursorStmt, err = db.PrepareContext(ctx, loadDBAppliedCursor); err != nil {
		return nil, fmt.Errorf("error preparing query LoadDBAppliedCursor: %w", err)
	}
	if q.loadMQPublishedCursorStmt, err = db.PrepareContext(ctx, loadMQPublishedCursor); err != nil {
		return nil, fmt.Errorf("error preparing query LoadMQPublishedCursor: %w", err)
	}
	if q.rejectOrderStmt, err = db.PrepareContext(ctx, rejectOrder); err != nil {
		return nil, fmt.Errorf("error preparing query RejectOrder: %w", err)
	}
	if q.saveDBAppliedCursorStmt, err = db.PrepareContext(ctx, saveDBAppliedCursor); err != nil {
		return nil, fmt.Errorf("error preparing query SaveDBAppliedCursor: %w", err)
	}
	if q.saveMQPublishedCursorStmt, err = db.PrepareContext(ctx, saveMQPublishedCursor); err != nil {
		return nil, fmt.Errorf("error preparing query SaveMQPublishedCursor: %w", err)
	}
	if q.saveSnapshotStmt, err = db.PrepareContext(ctx, saveSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query SaveSnapshot: %w", err)
	}
	if q.saveTradeStmt, err = db.PrepareContext(ctx, saveTrade); err != nil {
		return nil, fmt.Errorf("error preparing query SaveTrade: %w", err)
	}
	if q.updateAccountBalanceStmt, err = db.PrepareContext(ctx, updateAccountBalance); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountBalance: %w", err)
	}
	if q.updateOrderStatusStmt, err = db.PrepareContext(ctx, updateOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderStatus: %w", err)
	}
	if q.updateStockPriceStmt, err = db.PrepareContext(ctx, updateStockPrice); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStockPrice: %w", err)
	}
	if q.updateStockStatusStmt, err = db.PrepareContext(ctx, updateStockStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStockStatus: %w", err)
	}
	if q.upsertHoldingStmt, err = db.PrepareContext(ctx, upsertHolding); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertHolding: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateAccountStmt != nil {
		if cerr := q.activateAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateAccountStmt: %w", cerr)
		}
	}
	if q.deleteHoldingStmt != nil {
		if cerr := q.deleteHoldingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHoldingStmt: %w", cerr)
		}
	}
	if q.latestSnapshotStmt != nil {
		if cerr := q.latestSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing latestSnapshotStmt: %w", cerr)
		}
	}
	if q.loadDBAppliedCursorStmt != nil {
		if cerr := q.loadDBAppliedCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing loadDBAppliedCursorStmt: %w", cerr)
		}
	}
	if q.loadMQPublishedCursorStmt != nil {
		if cerr := q.loadMQPublishedCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing loadMQPublishedCursorStmt: %w", cerr)
		}
	}
	if q.rejectOrderStmt != nil {
		if cerr := q.rejectOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rejectOrderStmt: %w", cerr)
		}
	}
	if q.saveDBAppliedCursorStmt != nil {
		if cerr := q.saveDBAppliedCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveDBAppliedCursorStmt: %w", cerr)
		}
	}
	if q.saveMQPublishedCursorStmt != nil {
		if cerr := q.saveMQPublishedCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveMQPublishedCursorStmt: %w", cerr)
		}
	}
	if q.saveSnapshotStmt != nil {
		if cerr := q.saveSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveSnapshotStmt: %w", cerr)
		}
	}
	if q.saveTradeStmt != nil {
		if cerr := q.saveTradeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveTradeStmt: %w", cerr)
		}
	}
	if q.updateAccountBalanceStmt != nil {
		if cerr := q.updateAccountBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountBalanceStmt: %w", cerr)
		}
	}
	if q.updateOrderStatusStmt != nil {
		if cerr := q.updateOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateStockPriceStmt != nil {
		if cerr := q.updateStockPriceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStockPriceStmt: %w", cerr)
		}
	}
	if q.updateStockStatusStmt != nil {
		if cerr := q.updateStockStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStockStatusStmt: %w", cerr)
		}
	}
	if q.upsertHoldingStmt != nil {
		if cerr := q.upsertHoldingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertHoldingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	activateAccountStmt       *sql.Stmt
	deleteHoldingStmt         *sql.Stmt
	latestSnapshotStmt        *sql.Stmt
	loadDBAppliedCursorStmt   *sql.Stmt
	loadMQPublishedCursorStmt *sql.Stmt
	rejectOrderStmt           *sql.Stmt
	saveDBAppliedCursorStmt   *sql.Stmt
	saveMQPublishedCursorStmt *sql.Stmt
	saveSnapshotStmt          *sql.Stmt
	saveTradeStmt             *sql.Stmt
	updateAccountBalanceStmt  *sql.Stmt
	updateOrderStatusStmt     *sql.Stmt
	updateStockPriceStmt      *sql.Stmt
	updateStockStatusStmt     *sql.Stmt
	upsertHoldingStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		activateAccountStmt:       q.activateAccountStmt,
		deleteHoldingStmt:         q.deleteHoldingStmt,
		latestSnapshotStmt:        q.latestSnapshotStmt,
		loadDBAppliedCursorStmt:   q.loadDBAppliedCursorStmt,
		loadMQPublishedCursorStmt: q.loadMQPublishedCursorStmt,
		rejectOrderStmt:           q.rejectOrderStmt,
		saveDBAppliedCursorStmt:   q.saveDBAppliedCursorStmt,
		saveMQPublishedCursorStmt: q.saveMQPublishedCursorStmt,
		saveSnapshotStmt:          q.saveSnapshotStmt,
		saveTradeStmt:             q.saveTradeStmt,
		updateAccountBalanceStmt:  q.updateAccountBalanceStmt,
		updateOrderStatusStmt:     q.updateOrderStatusStmt,
		updateStockPriceStmt:      q.updateStockPriceStmt,
		updateStockStatusStmt:     q.updateStockStatusStmt,
		upsertHoldingStmt:         q.upsertHoldingStmt,
	}
}
