// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holding.sql

package sqlc

import (
	"context"
)

const upsertHolding = `-- name: UpsertHolding :exec
INSERT INTO user_stocks (account_id, stock_id, quantity, available_quantity, average, total_buy_amount)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  quantity = VALUES(quantity),
  available_quantity = VALUES(available_quantity),
  average = VALUES(average),
  total_buy_amount = VALUES(total_buy_amount)
`

type UpsertHoldingParams struct {
	AccountID         int32  `json:"account_id"`
	StockID           int32  `json:"stock_id"`
	Quantity          uint64 `json:"quantity"`
	AvailableQuantity uint64 `json:"available_quantity"`
	Average           uint64 `json:"average"`
	TotalBuyAmount    uint64 `json:"total_buy_amount"`
}

func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) error {
	_, err := q.exec(ctx, q.upsertHoldingStmt, upsertHolding,
		arg.AccountID,
		arg.StockID,
		arg.Quantity,
		arg.AvailableQuantity,
		arg.Average,
		arg.TotalBuyAmount,
	)
	return err
}
