// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CursorsType string

const (
	CursorsTypeEVENT CursorsType = "EVENT"
)

func (e *CursorsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CursorsType(s)
	case string:
		*e = CursorsType(s)
	default:
		return fmt.Errorf("unsupported scan type for CursorsType: %T", src)
	}
	return nil
}

type NullCursorsType struct {
	CursorsType CursorsType `json:"cursors_type"`
	Valid       bool        `json:"valid"` // Valid is true if CursorsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCursorsType) Scan(value interface{}) error {
	if value == nil {
		ns.CursorsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CursorsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCursorsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CursorsType), nil
}

type OrdersOrderType string

const (
	OrdersOrderTypeLIMIT  OrdersOrderType = "LIMIT"
	OrdersOrderTypeMARKET OrdersOrderType = "MARKET"
)

func (e *OrdersOrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderType(s)
	case string:
		*e = OrdersOrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderType: %T", src)
	}
	return nil
}

type NullOrdersOrderType struct {
	OrdersOrderType OrdersOrderType `json:"orders_order_type"`
	Valid           bool            `json:"valid"` // Valid is true if OrdersOrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderType), nil
}

type OrdersRejectReason string

const (
	OrdersRejectReasonINSUFFICIENTBALANCE OrdersRejectReason = "INSUFFICIENT_BALANCE"
	OrdersRejectReasonINSUFFICIENTSTOCK   OrdersRejectReason = "INSUFFICIENT_STOCK"
	OrdersRejectReasonPRICEOUTOFLIMIT     OrdersRejectReason = "PRICE_OUT_OF_LIMIT"
	OrdersRejectReasonSTOCKNOTTRADABLE    OrdersRejectReason = "STOCK_NOT_TRADABLE"
	OrdersRejectReasonALREADYPROCESSED    OrdersRejectReason = "ALREADY_PROCESSED"
)

func (e *OrdersRejectReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersRejectReason(s)
	case string:
		*e = OrdersRejectReason(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersRejectReason: %T", src)
	}
	return nil
}

type NullOrdersRejectReason struct {
	OrdersRejectReason OrdersRejectReason `json:"orders_reject_reason"`
	Valid              bool               `json:"valid"` // Valid is true if OrdersRejectReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersRejectReason) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersRejectReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersRejectReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersRejectReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersRejectReason), nil
}

type OrdersStatus string

const (
	OrdersStatusRECEIVED OrdersStatus = "RECEIVED"
	OrdersStatusOPEN     OrdersStatus = "OPEN"
	OrdersStatusFILLED   OrdersStatus = "FILLED"
	OrdersStatusCANCELED OrdersStatus = "CANCELED"
	OrdersStatusREPLACED OrdersStatus = "REPLACED"
	OrdersStatusREJECTED OrdersStatus = "REJECTED"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type OrdersTradingType string

const (
	OrdersTradingTypeBUY    OrdersTradingType = "BUY"
	OrdersTradingTypeSELL   OrdersTradingType = "SELL"
	OrdersTradingTypeEDIT   OrdersTradingType = "EDIT"
	OrdersTradingTypeCANCEL OrdersTradingType = "CANCEL"
)

func (e *OrdersTradingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersTradingType(s)
	case string:
		*e = OrdersTradingType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersTradingType: %T", src)
	}
	return nil
}

type NullOrdersTradingType struct {
	OrdersTradingType OrdersTradingType `json:"orders_trading_type"`
	Valid             bool              `json:"valid"` // Valid is true if OrdersTradingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersTradingType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersTradingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersTradingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersTradingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersTradingType), nil
}

type StocksStatus string

const (
	StocksStatusLISTED    StocksStatus = "LISTED"
	StocksStatusSUSPENDED StocksStatus = "SUSPENDED"
	StocksStatusDELISTED  StocksStatus = "DELISTED"
)

func (e *StocksStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StocksStatus(s)
	case string:
		*e = StocksStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StocksStatus: %T", src)
	}
	return nil
}

type NullStocksStatus struct {
	StocksStatus StocksStatus `json:"stocks_status"`
	Valid        bool         `json:"valid"` // Valid is true if StocksStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStocksStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StocksStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StocksStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStocksStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StocksStatus), nil
}

type UsersRole string

const (
	UsersRoleADMIN UsersRole = "ADMIN"
	UsersRoleUSER  UsersRole = "USER"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type Account struct {
	ID               int32     `json:"id"`
	UserID           int32     `json:"user_id"`
	AccountNumber    int32     `json:"account_number"`
	Balance          uint64    `json:"balance"`
	AvailableBalance uint64    `json:"available_balance"`
	CreatedAt        time.Time `json:"created_at"`
}

type Cursor struct {
	Type  CursorsType `json:"type"`
	Index int64       `json:"index"`
}

type Order struct {
	ID             int64                  `json:"id"`
	TargetID       sql.NullInt64          `json:"target_id"`
	AccountID      int32                  `json:"account_id"`
	StockID        int32                  `json:"stock_id"`
	Price          uint64                 `json:"price"`
	Quantity       uint64                 `json:"quantity"`
	FilledQuantity uint64                 `json:"filled_quantity"`
	OrderType      OrdersOrderType        `json:"order_type"`
	Status         OrdersStatus           `json:"status"`
	RejectReason   NullOrdersRejectReason `json:"reject_reason"`
	TradingType    OrdersTradingType      `json:"trading_type"`
	PublishedAt    sql.NullTime           `json:"published_at"`
	CreatedAt      time.Time              `json:"created_at"`
}

type RefreshToken struct {
	ID          int32  `json:"id"`
	UserID      int32  `json:"user_id"`
	HashedToken string `json:"hashed_token"`
}

type Snapshot struct {
	ID            int64     `json:"id"`
	State         []byte    `json:"state"`
	InputWalIndex uint64    `json:"input_wal_index"`
	CreatedAt     time.Time `json:"created_at"`
}

type Stock struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Price     uint64       `json:"price"`
	Status    StocksStatus `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type StockHistory struct {
	StockID    int32         `json:"stock_id"`
	Date       time.Time     `json:"date"`
	High       uint64        `json:"high"`
	Low        uint64        `json:"low"`
	Close      uint64        `json:"close"`
	Open       sql.NullInt64 `json:"open"`
	UpperLimit uint64        `json:"upper_limit"`
	LowerLimit uint64        `json:"lower_limit"`
}

type Trade struct {
	ID           int64     `json:"id"`
	StockID      int32     `json:"stock_id"`
	Price        uint64    `json:"price"`
	Quantity     uint64    `json:"quantity"`
	MakerOrderID int64     `json:"maker_order_id"`
	TakerOrderID int64     `json:"taker_order_id"`
	MatchedAt    time.Time `json:"matched_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	Role      UsersRole `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type UserStock struct {
	AccountID         int32  `json:"account_id"`
	StockID           int32  `json:"stock_id"`
	Quantity          uint64 `json:"quantity"`
	AvailableQuantity uint64 `json:"available_quantity"`
	Average           uint64 `json:"average"`
	TotalBuyAmount    uint64 `json:"total_buy_amount"`
}
