// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"
)

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?, filled_quantity = ?
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status         OrdersStatus `json:"status"`
	FilledQuantity uint64       `json:"filled_quantity"`
	ID             int64        `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.exec(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.Status, arg.FilledQuantity, arg.ID)
	return err
}
