// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"
)

const rejectOrder = `-- name: RejectOrder :exec
UPDATE orders
SET status = 'REJECTED', reject_reason = ?
WHERE id = ?
`

type RejectOrderParams struct {
	RejectReason NullOrdersRejectReason `json:"reject_reason"`
	ID           int64                  `json:"id"`
}

func (q *Queries) RejectOrder(ctx context.Context, arg RejectOrderParams) error {
	_, err := q.exec(ctx, q.rejectOrderStmt, rejectOrder, arg.RejectReason, arg.ID)
	return err
}

const updateOrderState = `-- name: UpdateOrderState :exec
UPDATE orders
SET status = ?, quantity = ?, filled_quantity = ?
WHERE id = ?
`

type UpdateOrderStateParams struct {
	Status         OrdersStatus `json:"status"`
	Quantity       uint64       `json:"quantity"`
	FilledQuantity uint64       `json:"filled_quantity"`
	ID             int64        `json:"id"`
}

func (q *Queries) UpdateOrderState(ctx context.Context, arg UpdateOrderStateParams) error {
	_, err := q.exec(ctx, q.updateOrderStateStmt, updateOrderState,
		arg.Status,
		arg.Quantity,
		arg.FilledQuantity,
		arg.ID,
	)
	return err
}
