// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"
)

const rejectOrder = `-- name: RejectOrder :exec
UPDATE orders
SET status = 'REJECTED', reject_reason = ?
WHERE id = ?
`

type RejectOrderParams struct {
	RejectReason NullOrdersRejectReason `json:"reject_reason"`
	ID           int64                  `json:"id"`
}

func (q *Queries) RejectOrder(ctx context.Context, arg RejectOrderParams) error {
	_, err := q.exec(ctx, q.rejectOrderStmt, rejectOrder, arg.RejectReason, arg.ID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?, filled_quantity = ?
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status         OrdersStatus `json:"status"`
	FilledQuantity uint64       `json:"filled_quantity"`
	ID             int64        `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.exec(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.Status, arg.FilledQuantity, arg.ID)
	return err
}
