// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ActivateAccount(ctx context.Context, id int32) error
	DeleteHolding(ctx context.Context, arg DeleteHoldingParams) error
	LatestSnapshot(ctx context.Context) (LatestSnapshotRow, error)
	LoadDBAppliedCursor(ctx context.Context) (int64, error)
	LoadMQPublishedCursor(ctx context.Context) (int64, error)
	RejectOrder(ctx context.Context, arg RejectOrderParams) error
	SaveDBAppliedCursor(ctx context.Context, index int64) error
	SaveMQPublishedCursor(ctx context.Context, index int64) error
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
	SaveTrade(ctx context.Context, arg SaveTradeParams) error
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateOrderState(ctx context.Context, arg UpdateOrderStateParams) error
	UpdateStockPrice(ctx context.Context, arg UpdateStockPriceParams) error
	UpdateStockStatus(ctx context.Context, arg UpdateStockStatusParams) error
	UpsertHolding(ctx context.Context, arg UpsertHoldingParams) error
}

var _ Querier = (*Queries)(nil)
