// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ActivateAccount(ctx context.Context, id int32) error
	LatestSnapshot(ctx context.Context) (LatestSnapshotRow, error)
	LoadCursor(ctx context.Context, type_ CursorsType) (int64, error)
	RejectOrder(ctx context.Context, arg RejectOrderParams) error
	SaveCursor(ctx context.Context, arg SaveCursorParams) error
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
	SaveTrade(ctx context.Context, arg SaveTradeParams) error
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateStockStatus(ctx context.Context, arg UpdateStockStatusParams) error
	UpsertHolding(ctx context.Context, arg UpsertHoldingParams) error
}

var _ Querier = (*Queries)(nil)
