// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	LatestSnapshot(ctx context.Context) (LatestSnapshotRow, error)
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
}

var _ Querier = (*Queries)(nil)
