// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package sqlc

import (
	"context"
)

const latestSnapshot = `-- name: LatestSnapshot :one
SELECT state, input_wal_index
FROM snapshots
ORDER BY id DESC
LIMIT 1
`

type LatestSnapshotRow struct {
	State         []byte `json:"state"`
	InputWalIndex uint64 `json:"input_wal_index"`
}

func (q *Queries) LatestSnapshot(ctx context.Context) (LatestSnapshotRow, error) {
	row := q.queryRow(ctx, q.latestSnapshotStmt, latestSnapshot)
	var i LatestSnapshotRow
	err := row.Scan(&i.State, &i.InputWalIndex)
	return i, err
}

const saveSnapshot = `-- name: SaveSnapshot :exec
INSERT INTO snapshots (state, input_wal_index)
VALUES (?, ?)
`

type SaveSnapshotParams struct {
	State         []byte `json:"state"`
	InputWalIndex uint64 `json:"input_wal_index"`
}

func (q *Queries) SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error {
	_, err := q.exec(ctx, q.saveSnapshotStmt, saveSnapshot, arg.State, arg.InputWalIndex)
	return err
}
