// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package sqlc

import (
	"context"
)

const updateStockStatus = `-- name: UpdateStockStatus :exec
UPDATE stocks
SET status = ?
WHERE id = ?
`

type UpdateStockStatusParams struct {
	Status StocksStatus `json:"status"`
	ID     int32        `json:"id"`
}

func (q *Queries) UpdateStockStatus(ctx context.Context, arg UpdateStockStatusParams) error {
	_, err := q.exec(ctx, q.updateStockStatusStmt, updateStockStatus, arg.Status, arg.ID)
	return err
}
