// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade.sql

package sqlc

import (
	"context"
	"time"
)

const saveTrade = `-- name: SaveTrade :execlastid
INSERT INTO trades (stock_id, price, quantity, maker_order_id, taker_order_id, matched_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type SaveTradeParams struct {
	StockID      int32     `json:"stock_id"`
	Price        uint64    `json:"price"`
	Quantity     uint64    `json:"quantity"`
	MakerOrderID int64     `json:"maker_order_id"`
	TakerOrderID int64     `json:"taker_order_id"`
	MatchedAt    time.Time `json:"matched_at"`
}

func (q *Queries) SaveTrade(ctx context.Context, arg SaveTradeParams) (int64, error) {
	result, err := q.exec(ctx, q.saveTradeStmt, saveTrade,
		arg.StockID,
		arg.Price,
		arg.Quantity,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MatchedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
