// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeTransfer = `-- name: CompleteTransfer :exec
UPDATE transfers
SET status = 'COMPLETED', completed_at = ?
WHERE id = ?
`

type CompleteTransferParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) CompleteTransfer(ctx context.Context, arg CompleteTransferParams) error {
	_, err := q.exec(ctx, q.completeTransferStmt, completeTransfer, arg.CompletedAt, arg.ID)
	return err
}

const rejectTransfer = `-- name: RejectTransfer :exec
UPDATE transfers
SET status = 'REJECTED', reject_reason = ?, completed_at = ?
WHERE id = ?
`

type RejectTransferParams struct {
	RejectReason NullTransfersRejectReason `json:"reject_reason"`
	CompletedAt  sql.NullTime              `json:"completed_at"`
	ID           int64                     `json:"id"`
}

func (q *Queries) RejectTransfer(ctx context.Context, arg RejectTransferParams) error {
	_, err := q.exec(ctx, q.rejectTransferStmt, rejectTransfer, arg.RejectReason, arg.CompletedAt, arg.ID)
	return err
}
